import { WORLD } from '../world/constants.js';
import { clamp, smoothNoise1D } from '../utils/math.js';

const EPS = 0.05;
const PX_PER_METER = 48;

export class WaterSolver {
  constructor(terrain, atmosphere, particles) {
    this.terrain = terrain;
    this.atmosphere = atmosphere;
    this.particles = particles;
    this.dx = WORLD.waterDx;
    this.n = Math.ceil(WORLD.width / this.dx);
    this.g = WORLD.gravity;

    this.h = new Float32Array(this.n);
    this.q = new Float32Array(this.n);
    this.bed = new Float32Array(this.n);
    this.eta = new Float32Array(this.n);
    this.pressure = new Float32Array(this.n);
    this.breaking = new Float32Array(this.n);
    this.sediment = new Float32Array(this.n);
    this.massFlux = new Float32Array(this.n + 1);
    // Hydrostatic reconstruction needs a cell-side momentum flux on each interface.
    // `momentumFluxLeft[k]` is the flux seen by the cell left of interface k;
    // `momentumFluxRight[k]` is the flux seen by the cell right of interface k.
    this.momentumFluxLeft = new Float32Array(this.n + 1);
    this.momentumFluxRight = new Float32Array(this.n + 1);
    this.sedimentFlux = new Float32Array(this.n + 1);
    this.nextH = new Float32Array(this.n);
    this.nextQ = new Float32Array(this.n);
    this.nextSediment = new Float32Array(this.n);

    this.baseSeaElevation = WORLD.height - WORLD.seaLevelY;
    this.time = 0;
    this.totalVolume = 0;
    this.kineticEnergy = 0;
    this.waveEnergy = 0;
    this.offshoreBoundary = null;
    this.structuralObstacles = [];
    this.refreshBed();
    this.resetWater();
  }

  refreshBed() {
    for (let i = 0; i < this.n; i++) {
      const x = (i + 0.5) * this.dx;
      const bedY = this.terrain.columnTopWorldYAt(x);
      this.bed[i] = WORLD.height - bedY;
    }

    for (const obstacle of this.structuralObstacles || []) {
      const progress = Math.max(0, Math.min(1, obstacle.progress ?? 1));
      if (progress <= 0.02) continue;
      const permeability = Math.max(0, Math.min(1, obstacle.permeability ?? 0));
      const effective = progress * (1 - permeability * 0.55);
      const crest = Math.max(0, (WORLD.height - obstacle.topY) * effective);
      const first = Math.max(0, Math.floor(obstacle.minX / this.dx));
      const last = Math.min(this.n - 1, Math.ceil(obstacle.maxX / this.dx));
      for (let i = first; i <= last; i++) {
        this.bed[i] = Math.max(this.bed[i], crest);
      }
    }
  }

  resetWater() {
    const sea = this.baseSeaElevation;
    for (let i = 0; i < this.n; i++) {
      this.h[i] = Math.max(0, sea - this.bed[i]);
      this.q[i] = 0;
      this.sediment[i] = 0;
      this.breaking[i] = 0;
    }
    this.updateDerived();
  }

  velocityAtIndex(i) {
    const h = this.h[i];
    return h > EPS ? this.q[i] / h : 0;
  }

  surfaceYAtIndex(i) {
    if (i < 0 || i >= this.n || this.h[i] <= EPS) return WORLD.height - this.bed[clamp(i, 0, this.n - 1)];
    return WORLD.height - (this.bed[i] + this.h[i]);
  }

  surfaceYAtX(x) {
    const fx = clamp(x / this.dx - 0.5, 0, this.n - 1);
    const i = Math.floor(fx);
    const j = Math.min(this.n - 1, i + 1);
    const t = fx - i;
    return this.surfaceYAtIndex(i) * (1 - t) + this.surfaceYAtIndex(j) * t;
  }

  depthAtX(x) {
    return this.h[clamp(Math.floor(x / this.dx), 0, this.n - 1)];
  }

  velocityAtX(x) {
    return this.velocityAtIndex(clamp(Math.floor(x / this.dx), 0, this.n - 1));
  }

  addImpulse(x, strength = 1) {
    const center = clamp(Math.floor(x / this.dx), 0, this.n - 1);
    const radius = 10;
    for (let d = -radius; d <= radius; d++) {
      const i = center + d;
      if (i < 0 || i >= this.n || this.h[i] <= EPS) continue;
      const w = Math.exp(-(d * d) / 22);
      this.q[i] += strength * 1200 * w * (d < 0 ? -1 : 1);
      // Perturbação de massa quase zero: crista e cava adjacentes.
      this.h[i] = Math.max(0, this.h[i] + strength * 1.8 * w * Math.sin(d * 0.65));
    }
  }

  addWaterAtIndex(i, amount) {
    if (i < 0 || i >= this.n || amount <= 0) return;
    this.h[i] += amount;
  }

  setOffshoreBoundary(value = null) {
    this.offshoreBoundary = value ? { ...value } : null;
  }

  setStructuralObstacles(obstacles = []) {
    this.structuralObstacles = obstacles.map((item) => ({ ...item }));
  }

  update(dt) {
    this.time += dt;
    this.refreshBed();

    const tidePx = this.atmosphere.tide * PX_PER_METER;
    const seaTarget = this.baseSeaElevation + tidePx;

    // Open-ocean boundary: nudges the first cells to the tide level and introduces
    // coherent swell generated by wind pressure over fetch.
    const windAbs = Math.abs(this.atmosphere.wind);
    const swellAmp = Math.min(10, Math.pow(windAbs / 8, 1.35) * 1.6) * (0.35 + this.atmosphere.gustiness);
    const swellFreq = 0.55 + Math.min(1.4, windAbs * 0.035);
    const external = this.offshoreBoundary;
    const backgroundSignal =
      Math.sin(this.time * swellFreq) * swellAmp +
      smoothNoise1D(this.time * 0.37, 51) * swellAmp * 0.55;
    const forcedSignal = external
      ? (external.waveAmplitudePx || 0) * (external.signal || 0) + (external.levelOffsetPx || 0)
      : 0;
    const boundaryEta = seaTarget + backgroundSignal * 0.35 + forcedSignal;

    for (let i = 0; i < Math.min(10, this.n); i++) {
      const targetH = Math.max(0, boundaryEta - this.bed[i]);
      const nudge = 1 - Math.exp(-dt * (4.4 - i * 0.31));
      this.h[i] += (targetH - this.h[i]) * nudge;
      const windCurrent = this.atmosphere.wind * 2.2;
      const waveCurrent = external?.currentVelocityPx || 0;
      const targetU = windCurrent + waveCurrent;
      this.q[i] += (targetU * this.h[i] - this.q[i]) * nudge * 0.16;
    }

    // Rainfall: 1 mm/h is intentionally scaled for gameplay while preserving
    // proportionality. Rain can create runoff on dry land because h exists above bed.
    if (this.atmosphere.rain > 0) {
      const rainDepthPxPerSec = this.atmosphere.rain * 0.00033;
      for (let i = 0; i < this.n; i++) this.h[i] += rainDepthPxPerSec * dt;
    }

    this.computeFluxes();

    const invDx = 1 / this.dx;
    for (let i = 0; i < this.n; i++) {
      let h = this.h[i] - dt * invDx * (this.massFlux[i + 1] - this.massFlux[i]);
      let q = this.q[i] - dt * invDx * (this.momentumFluxLeft[i + 1] - this.momentumFluxRight[i]);

      h = Math.max(0, h);
      if (h < EPS) {
        h = 0;
        q = 0;
      } else {
        let u = q / h;

        // Bed friction / quadratic drag. Stronger in shallow water.
        const hMeters = Math.max(0.05, h / PX_PER_METER);
        const uMeters = u / PX_PER_METER;
        const surfaceCell = this.terrain.surfaceCellForWorldX((i + 0.5) * this.dx);
        const surfaceIndex = surfaceCell.y < this.terrain.rows
          ? this.terrain.index(surfaceCell.x, surfaceCell.y)
          : -1;
        const vegetation = surfaceIndex >= 0 ? (this.terrain.vegetation?.[surfaceIndex] || 0) : 0;
        const cf = (0.008 + 0.018 / (1 + hMeters * 2.5)) * (1 + vegetation * 1.6);
        const duFrictionMeters = -cf * uMeters * Math.abs(uMeters) / hMeters;
        u += duFrictionMeters * PX_PER_METER * dt;

        // Wind stress: tau = rho_air * Cd * |V-U| (V-U), converted to acceleration.
        const windMeters = this.atmosphere.windAt(i / (this.n - 1));
        const waterUMeters = u / PX_PER_METER;
        const rel = windMeters - waterUMeters;
        const rhoAir = 1.225;
        const rhoWater = 1000;
        const cd = 0.0014 + 0.000045 * Math.min(30, Math.abs(windMeters));
        const tau = rhoAir * cd * rel * Math.abs(rel);
        const accelWind = tau / (rhoWater * hMeters);
        u += accelWind * PX_PER_METER * dt;

        // Spatially coherent pressure fluctuations seed capillary/gravity waves.
        const px = i * 0.075;
        const p0 = smoothNoise1D(px + this.time * (0.35 + windAbs * 0.012), 117);
        const p1 = smoothNoise1D(px + 0.08 + this.time * (0.35 + windAbs * 0.012), 117);
        const pressureGradient = (p1 - p0) / 0.08;
        u += -pressureGradient * this.atmosphere.gustiness * windAbs * 0.16 * dt;

        // CFL-aware velocity limiter. The gravity-wave speed c=sqrt(gh) is
        // part of the characteristic speed, so |u|+c must remain below dx/dt.
        const c = Math.sqrt(this.g * h);
        const maxCharacteristic = 0.92 * this.dx / dt;
        const maxU = Math.max(0, maxCharacteristic - c);
        u = clamp(u, -maxU, maxU);
        q = u * h;
      }

      this.nextH[i] = h;
      this.nextQ[i] = q;
    }

    this.h.set(this.nextH);
    this.q.set(this.nextQ);
    this.transportSediment(dt);
    this.applyBreaking(dt);
    this.updateDerived();
  }

  computeFluxes() {
    // Audusse-style hydrostatic reconstruction. The source term caused by bed
    // elevation is embedded as a side-specific correction to momentum flux.
    // This keeps a lake-at-rest (u=0, constant free surface) numerically still.
    const h0 = this.h[0];
    const q0 = this.q[0];
    const u0 = h0 > EPS ? q0 / h0 : 0;
    this.massFlux[0] = q0;
    const leftBoundaryMomentum = h0 > EPS ? q0 * u0 + 0.5 * this.g * h0 * h0 : 0;
    this.momentumFluxLeft[0] = leftBoundaryMomentum;
    this.momentumFluxRight[0] = leftBoundaryMomentum;

    for (let k = 1; k < this.n; k++) {
      const i = k - 1;
      const j = k;
      const hOrigL = this.h[i];
      const hOrigR = this.h[j];
      const etaL = this.bed[i] + hOrigL;
      const etaR = this.bed[j] + hOrigR;
      const z = Math.max(this.bed[i], this.bed[j]);
      const hL = Math.max(0, etaL - z);
      const hR = Math.max(0, etaR - z);
      const uL = hOrigL > EPS ? this.q[i] / hOrigL : 0;
      const uR = hOrigR > EPS ? this.q[j] / hOrigR : 0;
      const qL = hL * uL;
      const qR = hR * uR;
      const c = Math.max(Math.abs(uL) + Math.sqrt(this.g * hL), Math.abs(uR) + Math.sqrt(this.g * hR));

      const fMassL = qL;
      const fMassR = qR;
      const fMomL = hL > EPS ? qL * uL + 0.5 * this.g * hL * hL : 0;
      const fMomR = hR > EPS ? qR * uR + 0.5 * this.g * hR * hR : 0;
      const fMass = 0.5 * (fMassL + fMassR) - 0.5 * c * (hR - hL);
      const fMom = 0.5 * (fMomL + fMomR) - 0.5 * c * (qR - qL);

      this.massFlux[k] = fMass;
      this.momentumFluxLeft[k] = fMom + 0.5 * this.g * (hOrigL * hOrigL - hL * hL);
      this.momentumFluxRight[k] = fMom + 0.5 * this.g * (hOrigR * hOrigR - hR * hR);
    }

    const last = this.n - 1;
    const hN = this.h[last];
    const qN = this.q[last];
    const uN = hN > EPS ? qN / hN : 0;
    this.massFlux[this.n] = qN;
    const rightBoundaryMomentum = hN > EPS ? qN * uN + 0.5 * this.g * hN * hN : 0;
    this.momentumFluxLeft[this.n] = rightBoundaryMomentum;
    this.momentumFluxRight[this.n] = rightBoundaryMomentum;
  }

  transportSediment(dt) {
    // Upwind advection of suspended sediment mass.
    this.sedimentFlux[0] = 0;
    for (let k = 1; k < this.n; k++) {
      const u = 0.5 * (this.velocityAtIndex(k - 1) + this.velocityAtIndex(k));
      const donor = u >= 0 ? k - 1 : k;
      this.sedimentFlux[k] = u * this.sediment[donor];
    }
    this.sedimentFlux[this.n] = 0;

    const invDx = 1 / this.dx;
    for (let i = 0; i < this.n; i++) {
      const advected = this.sediment[i] - dt * invDx * (this.sedimentFlux[i + 1] - this.sedimentFlux[i]);
      // Small turbulent diffusion reduces numerical clumping.
      const left = this.sediment[Math.max(0, i - 1)];
      const right = this.sediment[Math.min(this.n - 1, i + 1)];
      const diffused = advected + (left + right - 2 * this.sediment[i]) * dt * 0.65;
      this.nextSediment[i] = Math.max(0, diffused);
    }
    this.sediment.set(this.nextSediment);
  }

  applyBreaking(dt) {
    for (let i = 1; i < this.n - 1; i++) {
      const h = this.h[i];
      if (h <= EPS) {
        this.breaking[i] = 0;
        continue;
      }
      const u = this.q[i] / h;
      const eta = this.bed[i] + h;
      // A dry neighbour contains bed elevation, not a free surface. Reusing the
      // current eta on a dry side prevents a static shoreline from being mistaken
      // for a breaking wave merely because the beach bed rises steeply.
      const etaL = this.h[i - 1] > EPS ? this.bed[i - 1] + this.h[i - 1] : eta;
      const etaR = this.h[i + 1] > EPS ? this.bed[i + 1] + this.h[i + 1] : eta;
      const slope = Math.abs(etaR - etaL) / (2 * this.dx);
      const froude = Math.abs(u) / Math.max(1, Math.sqrt(this.g * h));
      const shallowFactor = clamp(1 - h / 105, 0, 1);
      const criterion = Math.max(slope * 1.7, froude * 0.85) * (0.55 + shallowFactor * 0.85);
      const intensity = clamp((criterion - 0.35) / 0.75, 0, 1);
      this.breaking[i] += (intensity - this.breaking[i]) * (1 - Math.exp(-dt * 9));

      if (this.breaking[i] > 0.08) {
        const dissipation = Math.exp(-dt * (0.8 + this.breaking[i] * 4.8));
        this.q[i] *= dissipation;
        if (this.particles && Math.random() < this.breaking[i] * dt * 10) {
          this.particles.spawnFoam(
            (i + 0.5) * this.dx,
            this.surfaceYAtIndex(i),
            u * 0.28,
            -25 - this.breaking[i] * 55,
            this.breaking[i]
          );
        }
      }
    }
  }

  updateDerived() {
    let volume = 0;
    let kinetic = 0;
    let waveEnergy = 0;
    const meanSea = this.baseSeaElevation + this.atmosphere.tide * PX_PER_METER;
    for (let i = 0; i < this.n; i++) {
      const h = this.h[i];
      const u = h > EPS ? this.q[i] / h : 0;
      this.eta[i] = this.bed[i] + h;
      this.pressure[i] = h * 1000 * 9.81 / PX_PER_METER;
      volume += h * this.dx;
      kinetic += 0.5 * h * u * u * this.dx;
      const dEta = this.eta[i] - meanSea;
      waveEnergy += 0.5 * this.g * dEta * dEta * this.dx;
    }
    this.totalVolume = volume;
    this.kineticEnergy = kinetic;
    this.waveEnergy = waveEnergy;
  }

  serialize() {
    return {
      h: Array.from(this.h),
      q: Array.from(this.q),
      sediment: Array.from(this.sediment),
      time: this.time
    };
  }

  hydrate(data) {
    if (!data) return;
    this.refreshBed();
    if (data.h?.length === this.h.length) this.h.set(data.h);
    if (data.q?.length === this.q.length) this.q.set(data.q);
    if (data.sediment?.length === this.sediment.length) this.sediment.set(data.sediment);
    this.time = Number(data.time || 0);
    this.updateDerived();
  }
}
