export const JOB_STATES={PLANNED:"PLANNED",WAITING_RESOURCES:"WAITING_RESOURCES",WAITING_WORKERS:"WAITING_WORKERS",BUILDING:"BUILDING",PAUSED:"PAUSED",COMPLETED:"COMPLETED",CANCELLED:"CANCELLED",FAILED:"FAILED"};
let sequence=1;
export class ConstructionJob {
  constructor({id,type="BUILD",blueprint,laborHours=1,workersRequired=2,desiredWorkers=workersRequired,priority="NORMAL",state=JOB_STATES.PLANNED,progress=0,assignedWorkers=0,createdAt=Date.now()}={}){this.id=id||"job-"+sequence++;this.type=type;this.blueprint=blueprint;this.laborHours=Math.max(.02,laborHours);this.workersRequired=Math.max(1,workersRequired);this.desiredWorkers=Math.max(1,desiredWorkers);this.priority=priority;this.state=state;this.progress=progress;this.assignedWorkers=assignedWorkers;this.createdAt=createdAt;}
  effectiveWorkers(){return Math.pow(Math.max(0,this.assignedWorkers),.75);}
  update(gameHours){if(["PAUSED","CANCELLED","FAILED","COMPLETED"].includes(this.state))return false;if(this.assignedWorkers<=0){this.state="WAITING_WORKERS";return false;}this.state="BUILDING";const baseline=Math.pow(this.workersRequired,.75),productivity=this.effectiveWorkers()/Math.max(.1,baseline);this.progress=Math.min(1,this.progress+gameHours*productivity/this.laborHours);if(this.progress>=1){this.state="COMPLETED";return true;}return false;}
  remainingHours(){if(this.progress>=1)return 0;const baseline=Math.pow(this.workersRequired,.75),p=this.effectiveWorkers()/Math.max(.1,baseline);return p<=0?Infinity:(1-this.progress)*this.laborHours/p;}
  serialize(){return {id:this.id,type:this.type,blueprint:this.blueprint,laborHours:this.laborHours,workersRequired:this.workersRequired,desiredWorkers:this.desiredWorkers,priority:this.priority,state:this.state,progress:this.progress,assignedWorkers:this.assignedWorkers,createdAt:this.createdAt,targetAssemblyId:this.targetAssemblyId||null};}
}
