import { SimulationClock } from "./SimulationClock.js";import { SIMULATION_STATES } from "./SimulationState.js";import { BaselineSnapshot } from "./BaselineSnapshot.js";import { CheckpointManager } from "./CheckpointManager.js";
export class SimulationRunner{
 constructor({app}){this.app=app;this.clock=new SimulationClock();this.state=SIMULATION_STATES.EDIT;this.baseline=new BaselineSnapshot();this.checkpoints=new CheckpointManager({intervalSeconds:30,max:24});this.speed=1;this.pendingComplete=false;}
 start(){const a=this.app;if(this.state===SIMULATION_STATES.COMPLETED&&this.baseline.value)this.baseline.restore(a.engine,a);if(!this.baseline.value||a.experiments.dirty)this.baseline.capture(a.engine,a);this.clock.reset();this.checkpoints.reset();this.pendingComplete=false;a.prepareRun();a.experiments.dirty=false;this.state=SIMULATION_STATES.RUNNING;a.experiments.state="RUNNING";a.engine.setSimulationSpeed(this.speed);a.engine.setRunning(true);return true;}
 pause(){if(this.state!==SIMULATION_STATES.RUNNING)return false;this.state=SIMULATION_STATES.PAUSED;this.app.experiments.state="PAUSED";this.app.engine.setRunning(false);return true;}
 resume(){if(this.state!==SIMULATION_STATES.PAUSED)return false;this.state=SIMULATION_STATES.RUNNING;this.app.experiments.state="RUNNING";this.app.engine.setRunning(true);return true;}
 setSpeed(v){this.speed=Math.max(.25,Math.min(8,Number(v)||1));this.app.engine.setSimulationSpeed(this.speed);}
 reset(){this.app.engine.setRunning(false);if(this.baseline.value)this.baseline.restore(this.app.engine,this.app);this.app.resetTransient();this.clock.reset();this.pendingComplete=false;this.state=SIMULATION_STATES.EDIT;this.app.experiments.state="EDIT";return true;}
 step(){if(this.state!==SIMULATION_STATES.PAUSED&&this.state!==SIMULATION_STATES.EDIT)return false;this.app.engine.setRunning(false);this.app.engine.step(1/120);return true;}
 update(dt){if(this.state!==SIMULATION_STATES.RUNNING)return;this.clock.update(dt);this.app.disasterController.update(this.clock.elapsedSeconds);if(this.clock.elapsedMinutes>=this.app.experiments.current.disaster.duration)this.pendingComplete=true;}
 postPhysics(dt){if(this.state!==SIMULATION_STATES.RUNNING)return;const sample=this.app.metrics.sample(dt,this.app);if(sample)this.app.replay.recordSample(this.clock.elapsedSeconds,sample);const checkpoint=this.checkpoints.maybeCapture(this.clock.elapsedSeconds,()=>this.app.captureReplayState());if(checkpoint)this.app.replay.addCheckpoint(checkpoint);if(this.pendingComplete)this.complete();}
 complete(){if(this.state===SIMULATION_STATES.COMPLETED)return;this.app.engine.setRunning(false);const result=this.app.finishRun();this.state=SIMULATION_STATES.COMPLETED;this.app.experiments.addRun(result);}
 snapshot(){return {state:this.state,elapsedMinutes:this.clock.elapsedMinutes,elapsedSeconds:this.clock.elapsedSeconds,clock:this.clock.format(),durationMinutes:this.app.experiments.current.disaster.duration,speed:this.speed,progress:Math.min(1,this.clock.elapsedMinutes/Math.max(1,this.app.experiments.current.disaster.duration))};}
}
