import { ChallengeDefinition } from "./ChallengeDefinition.js";import { ChallengeEvaluator } from "./ChallengeEvaluator.js";import { ConstraintEvaluator } from "./ConstraintEvaluator.js";
export const DEFAULT_CHALLENGES=[
 new ChallengeDefinition({id:"protect-hospital",title:"Proteja o hospital",description:"Mantenha os danos urbanos sob controle durante uma ressaca severa.",template:"coastal-town",budget:50000,event:{waveHeight:4,wavePeriod:9,stormSurge:1,tide:.4,windSpeed:90,rainfall:35,duration:160},objectives:[{metric:"metrics.buildingsDestroyed",operator:"==",value:0},{metric:"metrics.peakFloodedArea",operator:"<",value:.28}]}),
 new ChallengeDefinition({id:"keep-city-dry",title:"Cidade seca",description:"Mantenha menos de 20% da zona urbana inundada.",template:"low-lying-city",budget:60000,event:{waveHeight:3.5,wavePeriod:9,stormSurge:1.1,windSpeed:75,rainfall:45,duration:180},objectives:[{metric:"metrics.peakFloodedArea",operator:"<",value:.2}]}),
 new ChallengeDefinition({id:"save-port",title:"Porto operacional",description:"Proteja a infraestrutura portuária durante ondas longas.",template:"harbor",budget:75000,event:{waveHeight:4.5,wavePeriod:11,stormSurge:.8,windSpeed:95,rainfall:20,duration:180},objectives:[{metric:"metrics.buildingsDestroyed",operator:"==",value:0}]}),
 new ChallengeDefinition({id:"rain-bomb",title:"Rain Bomb",description:"Chuva extrema sobre solo saturado.",template:"river-mouth",budget:45000,event:{waveHeight:.8,wavePeriod:6,stormSurge:.1,windSpeed:35,rainfall:120,duration:90},environment:{soilSaturation:.9},objectives:[{metric:"metrics.peakFloodedArea",operator:"<",value:.3}]}),
 new ChallengeDefinition({id:"natural-defenses",title:"Defesa natural",description:"Proteja a costa sem concreto.",template:"coastal-town",budget:40000,event:{waveHeight:3.2,wavePeriod:8,stormSurge:.8,windSpeed:70,rainfall:25,duration:150},constraints:{forbiddenTools:["CONCRETE_WALL"]},objectives:[{metric:"metrics.peakFloodedArea",operator:"<",value:.28}]})
];
export class ChallengeManager{constructor(c=DEFAULT_CHALLENGES){this.challenges=c;this.active=null;this.lastEvaluation=null;}start(id){this.active=this.challenges.find(c=>c.id===id)||null;this.lastEvaluation=null;return this.active;}evaluate(result,context){if(!this.active)return null;const constraints=ConstraintEvaluator.evaluate(this.active,context),objectives=ChallengeEvaluator.evaluate(this.active,result,context);this.lastEvaluation={completed:constraints.valid&&objectives.completed,constraints,objectives:objectives.objectives};return this.lastEvaluation;}clear(){this.active=null;this.lastEvaluation=null;}snapshot(){return {active:this.active?{...this.active}:null,evaluation:this.lastEvaluation,available:this.challenges.map(c=>({id:c.id,title:c.title,description:c.description,budget:c.budget}))};}}
